version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=changeme
      - ELASTICSEARCH_USERNAME=elastic
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    environment:
      - xpack.monitoring.enabled=false
      - xpack.management.enabled=false
      - xpack.management.elasticsearch.hosts=["http://elasticsearch:9200"]
    ports:
      - "5044:5044"
    networks:
      - elk
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  microservice:
    build: ./gestion-reservas
    ports:
      - "3000:3000"
    networks:
      - elk
    depends_on:
      - logstash

  frontend:
    build: ./gestion-reservas-frontend
    ports:
      - "3001:3001"
    networks:
      - elk

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
